version: "3.9"
services:
  app1:
    image: app
    network_mode: bridge
    environment:
      - BOOTSTRAP_PEERS=${BOOTSTRAP}
  app2:
    image: app
    network_mode: bridge
    environment:
      - BOOTSTRAP_PEERS=${BOOTSTRAP}
  app3:
    image: app
    network_mode: bridge
    environment:
      - BOOTSTRAP_PEERS=${BOOTSTRAP}
  #app4:
  #  image: app
  #  network_mode: bridge
  #  environment:
  #    - BOOTSTRAP_PEERS=${BOOTSTRAP}